### ISSUE TITLE
Remove /var/lib/insights and associated etag files upon package removal/upgrade

### ISSUE THREAD

**Issue by kylape** [RedHatInsights/insights-client#55]
There are some edge cases that cause issues if dynamically downloaded eggs are not cleaned up after an upgrade.  Example:  User disables updates after downloading one or more egg.  This causes the RPM-delivered egg to be more recent than the downloaded one, but it will never be used.

If a user removes insights-client, there is no need to keep the old eggs around.  They should be removed.

**Comment by gravitypriest** [comment]
Fixed

https://github.com/RedHatInsights/insights-client/commit/6db39df92264696fb4e1c9861f6e3dc17d6aa289
