### ISSUE TITLE
PIP install fails on non-RedHat systems

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-client#66]
setuptools for _insights-client_ contain [some logic](https://github.com/RedHatInsights/insights-client/blob/81918d9ca2c4ed01fa979f9bcdd4b0c55f840372/setup.py#L62) depending on RHEL version. To determine the version, a `/etc/redhat-release` file is [expected](https://github.com/RedHatInsights/insights-client/blob/81918d9ca2c4ed01fa979f9bcdd4b0c55f840372/insights_client/major_version.py#L5) to exist. This is the only piece of `setup.py` that prevents running `pip install -e .` on a non-RHEL system.

I’d suggest either alter the [`major_version`](https://github.com/RedHatInsights/insights-client/blob/81918d9ca2c4ed01fa979f9bcdd4b0c55f840372/insights_client/major_version.py#L5) function to return `None` on systems where the version can’t be determined or throw/catch an appropriate exception in [`setup.py#get_version`](https://github.com/RedHatInsights/insights-client/blob/81918d9ca2c4ed01fa979f9bcdd4b0c55f840372/setup.py#L10), which might be more pythonic.

Even though installing insights-client package on a non-RHEL system doesn’t make much sense per se, it can be still used to run tests. Those are pure Python and anything outside the “sandbox” should be mocked anyway.

**Comment by ptoscano** [comment]
`insights-client` does not have a `setuptools`-based buildsystem anymore; now it uses `meson` for RHEL 8 & 9 (current `master` branch), and in old branches for RHEL 6 & 7 autotools are used.
