### ISSUE TITLE
Be able to work without a packed egg

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-client#73]
It’s rather unpractical for development to build a new egg every time code changes. The egg is essentially only packed _insights-core_ folder. Thus it shouldn’t be too difficult to tweak the client, so it would accept such folder instead of the one-file package. The client could be then run with something like

```
EGG=/home/stomsa/dev/insights-core insights-client
```

instead of

```
EGG=/etc/insights-client/rpm.egg insights-client
```

**Comment by kyle-walker** [comment]
Doesn't #136 resolve this Issue?

**Comment by Glutexo** [comment]
It does! Good catch, thanks! Closing.
